export const LOGIN = "LOGIN";
export const UPDATE_AUTH_FIELD = "UPDATE_AUTH_FIELD";
export const ASYNC_START = "ASYNC_START";
export const ASYNC_END = "ASYNC_END";
export const INIT_AUTH = "INIT_AUTH";
export const LOGOUT = "LOGOUT";
export const USER_FETCHED = "USER_FETCHED";
export const USER_UPDATED = "USER_UPDATED";

export const CATEGORY_LOADED = "CATEGORY_LOADED";
export const PRODUCTS_LOADED = "PRODUCTS_LOADED";

export const APP_LOADED = "APP_LOADED";
export const APP_LOADING = "APP_LOADING";
export const ADDRESS_SELECTED = "ADDRESS_SELECTED";

export const ADDRESS_LOADED = "ADDRESS_LOADED";
export const ADDRESS_SAVED = "ADDRESS_SAVED";
export const ADDRESS_UPDATED = "ADDRESS_UPDATED";
export const ADDRESS_DELETED = "ADDRESS_DELETED";
export const DELIVERY_ADDRESS_REMOVED = "DELIVERY_ADDRESS_REMOVED";

export const CART_PRODUCT_ADDED = "CART_PRODUCT_ADDED";
export const CART_PRODUCT_REMOVED = "CART_PRODUCT_REMOVED";
export const CART_PRODUCT_UPDATED = "CART_PRODUCT_UPDATED";
export const CART_COUPONS_LOADED = "CART_COUPONS_LOADED";
export const CART_COUPON_APPLIED = "CART_COUPON_APPLIED";
export const CART_TAX_APPLIED = "CART_TAX_APPLIED";
export const CART_EVALUATED = "CART_EVALUATED";
export const CART_CLEARED = "CART_CLEARED";

export const ALL_PRODUCTS_LOADED = "ALL_PRODUCTS_LOADED";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDERS_LOADED = "ORDERS_LOADED";
export const ORDER_CANCELLED = "ORDER_CANCELLED";
export const ORDER_PLACED_CLEARED = "ORDER_PLACED_CLEARED";
export const SLIDER_IMAGES_LOADED = "SLIDER_IMAGES_LOADED";

