export const LOGIN = "LOGIN";
export const UPDATE_AUTH_FIELD = "UPDATE_AUTH_FIELD";
export const ASYNC_START = "ASYNC_START";
export const ASYNC_END = "ASYNC_END";
export const INIT_AUTH = "INIT_AUTH";
export const LOGOUT = "LOGOUT";
export const USER_FETCHED = "USER_FETCHED";
export const USER_UPDATED = "USER_UPDATED";

export const CATEGORY_LOADED = "CATEGORY_LOADED";
export const PRODUCTS_LOADED = "PRODUCTS_LOADED";

export const APP_LOADED = "APP_LOADED"
export const APP_LOADING = "APP_LOADING"
export const ADDRESS_SELECTED = "ADDRESS_SELECTED"

export const ADDRESS_LOADED = "ADDRESS_LOADED"
export const ADDRESS_SAVED = "ADDRESS_SAVED"
export const ADDRESS_UPDATED = "ADDRESS_UPDATED"
export const ADDRESS_DELETED = "ADDRESS_DELETED"